In [1]:
import torch
import numpy as np

Tensors

In [18]:
tensor_2d = torch.randn(10, 2)
tensor_2d

tensor([[-1.5003, -1.2413],
        [-0.4814, -0.5129],
        [ 0.7744,  0.6409],
        [-0.2630, -1.1971],
        [-0.9673,  1.6916],
        [-0.4411, -0.4375],
        [-2.2640,  1.6397],
        [-0.6776,  0.6762],
        [-1.4219, -0.2786],
        [-1.4646,  0.2825]])

In [26]:
tensor_3d = torch.zeros(5, 2, 3)
tensor_3d

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [36]:
torch.cuda.current_device()

0

In [51]:
tensor = torch.arange(30)
tensor.reshape(6, -1)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])

In [ ]:
tensor.view